server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG  # shows route matching
    org.springframework.web: DEBUG            # controller mapping
    reactor.netty: DEBUG                      # shows request flow
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE   # Route matched: profile-service or Not matched

spring:
  application:
    name: gateway-service

  cloud:
    consul:
      host: localhost
      port: 8500

      discovery:
        enabled: true
        register: true
        service-name: api-gateway
        prefer-ip-address: true   # health checks in consul config is failing as its taking Saranas_Vivo hostname, other ways: hardcode discovery.ip-address or discovery.hostname.

      config:
        enabled: false
        format: yaml
        prefix: config
        default-context: application

    gateway:
      discovery:
        locator:
          enabled: false   # This automatically creates routes, not production-safe
          lower-case-service-id: true

      routes:
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/profile/**
          filters:
            - StripPrefix=2   # Incoming Rqst: /api/profile/users After Gateway: /users

        - id: show-service
          uri: lb://show-service
          predicates:
            - Path=/api/show/**
          filters:
            - StripPrefix=2

        - id: homepage-service
          uri: lb://homepage-service
          predicates:
            - Path=/api/home/**
          filters:
            - StripPrefix=2

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/booking/**
          filters:
            - StripPrefix=2

      globalcors:
        cors-configurations:
          '[/**]':
              allowedOrigins: "http://localhost:5173"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - PATCH
                - OPTIONS
              allowedHeaders: "*"
              allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        # include: health,info
        include: "*"
